In [1]:
import torch

### Creating Activation Function

In [2]:
def activation(x):
    """
    Sigmoid Activation Function
    
    Arguments
    ----------
    x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))    

### Generating Random Data

In [3]:
torch.manual_seed(7)

# Creating a single datapoint with 5 features
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [5]:
# Output of the Network
y = activation(torch.sum(features*weights) + bias)
print(y)

tensor([[0.1595]])


In [6]:
# Using Matrix Multiplication - torch.mm() method
# weights.view() method resizes the array which is reqd for the matrix multiplication
y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

tensor([[0.1595]])


### Multi-Layer Network

In [7]:
torch.manual_seed(7)

# Single datapoint with 3 features
features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

# Weights for hidden(W1) and Output(W2) Layer Respectively
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

# Bias for hidden(B1) and Output(B2) Layer Respectively
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

In [12]:
y = activation(torch.mm(activation(torch.mm(features, W1) + B1), W2) + B2)
print(y)

tensor([[0.3171]])


### Torch and Numpy

In [13]:
import numpy as np

In [14]:
a = np.random.rand(4,3)
a

array([[0.10941515, 0.11137991, 0.6052961 ],
       [0.21596217, 0.33850907, 0.18264544],
       [0.21387491, 0.58374451, 0.68612636],
       [0.565554  , 0.2021865 , 0.77320554]])

In [15]:
b = torch.from_numpy(a)
b

tensor([[0.1094, 0.1114, 0.6053],
        [0.2160, 0.3385, 0.1826],
        [0.2139, 0.5837, 0.6861],
        [0.5656, 0.2022, 0.7732]], dtype=torch.float64)

The memory is shared between the Numpy array and the Torch Tensor. Therefore, if the values are changed in-place in one object, it changes for other as well.

In [16]:
b.mul_(2)

tensor([[0.2188, 0.2228, 1.2106],
        [0.4319, 0.6770, 0.3653],
        [0.4277, 1.1675, 1.3723],
        [1.1311, 0.4044, 1.5464]], dtype=torch.float64)

In [17]:
a

array([[0.21883031, 0.22275983, 1.2105922 ],
       [0.43192434, 0.67701815, 0.36529088],
       [0.42774982, 1.16748902, 1.37225271],
       [1.131108  , 0.404373  , 1.54641109]])