In [1]:
import sys
sys.executable

'c:\\users\\vatsa\\miniconda3\\envs\\pytorch\\python.exe'

In [2]:
import torch

### Creating Activation Function

In [3]:
def activation(x):
    """
    Sigmoid Activation Function
    
    Arguments
    ----------
    x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))    

### Generating Random Data

In [4]:
torch.manual_seed(7)

# Creating a single datapoint with 5 features
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [5]:
# Output of the Network
y = activation(torch.sum(features*weights) + bias)
print(y)

tensor([[0.1595]])


In [6]:
# Using Matrix Multiplication - torch.mm() method
# weights.view() method resizes the array which is reqd for the matrix multiplication
y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

tensor([[0.1595]])


### Multi-Layer Network

In [7]:
torch.manual_seed(7)

# Single datapoint with 3 features
features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

# Weights for hidden(W1) and Output(W2) Layer Respectively
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

# Bias for hidden(B1) and Output(B2) Layer Respectively
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

In [8]:
y = activation(torch.mm(activation(torch.mm(features, W1) + B1), W2) + B2)
print(y)

tensor([[0.3171]])


### Torch and Numpy

In [9]:
import numpy as np

In [10]:
a = np.random.rand(4,3)
a

array([[0.55899785, 0.22230766, 0.41100208],
       [0.43082374, 0.17821791, 0.09061701],
       [0.47827169, 0.54575863, 0.21712669],
       [0.56196468, 0.14767502, 0.77810277]])

In [11]:
b = torch.from_numpy(a)
b

tensor([[0.5590, 0.2223, 0.4110],
        [0.4308, 0.1782, 0.0906],
        [0.4783, 0.5458, 0.2171],
        [0.5620, 0.1477, 0.7781]], dtype=torch.float64)

The memory is shared between the Numpy array and the Torch Tensor. Therefore, if the values are changed in-place in one object, it changes for other as well.

In [12]:
b.mul_(2)

tensor([[1.1180, 0.4446, 0.8220],
        [0.8616, 0.3564, 0.1812],
        [0.9565, 1.0915, 0.4343],
        [1.1239, 0.2954, 1.5562]], dtype=torch.float64)

In [13]:
a

array([[1.11799569, 0.44461532, 0.82200415],
       [0.86164749, 0.35643581, 0.18123402],
       [0.95654338, 1.09151726, 0.43425337],
       [1.12392936, 0.29535003, 1.55620554]])